services:
  sumoney:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sumoney-backend
    env_file:
      - .env
    ports:
      - "8888:8080"
    depends_on:
      sumoney-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - money

  sumoney-postgres:
    image: postgres:17
    container_name: money-postgres-sumoney
    environment:
      POSTGRES_DB: money
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - money_service_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d money"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - money

  minio:
    image: minio/minio:latest
    container_name: sumoney-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - money

volumes:
  money_service_postgres:
  minio_data:

networks:
  money:
    driver: bridge