spring.application.name=SuMoney

spring.datasource.url=jdbc:postgresql://money-postgres-sumoney:5432/money
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name= org.postgresql.Driver

minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=receipts

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=fdvnsdnvrcwvnnj30i84tu4985ugjwoiqqjsdfwvil3rhf90o34p=efpebpl?FLAOKEQR3
jwt.duration=900
refresh.duration=30 