spring.application.name=SuMoney

spring.datasource.url=jdbc:postgresql://money-postgres-sumoney:5432/money
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name= org.postgresql.Driver
